schema: schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    default: https://subgraph.satsuma-prod.com/5636b4e4f174/2f2cac0b14bf2592543789045a02fa2ea9f0a91ab1f6e23e8859e8e618e6d1a7/real-functions-manager1/api